language: rust
rust: stable

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
  - master

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- travis-cargo build
- travis-cargo test
- travis-cargo doc

after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo --verify

env:
  global:
    secure: YyFrYr5q2y6B3bIFDoEZk0bH/Ml/xKK97q0MS3juioLOjKPmECeHFoXbAOdGBXC3GEjr5006MgseSGsph/Cl+Vi/rAUgzK93ePDB85mHhfGV0/Sa6bs7dgI/V3W26bvIMeZVZOPQqN4VTbb+lVSBp3a2+EyTCXIObbRX+hNlsF63ElxccVTppi2IBVgH9pIZmzrct9thzQgLnhObUw0sp+CgAYIfHKqpH3mOwO+snMBtH6YJB2U7eSqJHVSguKGb/VR/GOaczLOLLXjDV2KJCTxV16retFcGCTKy0yWZZ/W2mwHxhEJ3h7j2zKiMeACJqjtGPuapQIy1a0AQ+tCxvLy8NerfroZ4xQ/H1XEUg6Pql7y6X4GoNwYAcw5kIJCr+Iz3OTO/kpNWDtoOvUTFhQiR6a7n0+p+srSZ5kR2loKvBZrrtB8v2HxQNqhW/jVDeOt06QJse5FCGFfydNy64X/CcyXKH2uY/m6n2SuG2Gb+C/XH9xDbTyEu3XiX34WgjLlrEimmOdqApMLTY7jvtTnSDcxA0fyI3DJwGmgUmupgKEcfuQzDT75WoZMLa8l28lYuUh3FgMD/irj1inhzNogBFcPXVovasz9jYnXkGKsE+qpR2z6WGJk28mxM99dbiAE/uQ3LxXvvOwnq9DGJHhhuiGvO0zOiDLXHKVMRbSI=
